FROM centos:8

RUN yum -y install openssh-server

RUN useradd remote-user && \
    echo "remote-user:1234" | chpasswd && \
    mkdir /home/remote-user/.ssh && \
    chmod 700 /home/remote-user/.ssh

COPY remote-key.pub /home/remote-user/.ssh/authorized_keys

RUN chown remote_user:remote-user   -R /home/remot-user && \
    chmod 400 /home/remote-user/.ssh/authorized_keys

RUN ssh-keygen -A && rm -rf /run/nologin

RUN yum -y install mysql

RUN yum -y install epel-release && \
    yum -y install python3-pip && \
    pip3 install --upgrade pip && \
    pip3 install awscli

CMD /usr/sbin/sshd -D
